### ISSUE TITLE
Neatness counts.

### ISSUE THREAD

**Issue by CozyLife** [sudocode/ohmy-auth#23]
First, let me say thank you for writing this script, as it's saved me the hassle of writing my own. However, I just want to mention that neatness counts when you program. I'm literally spending hours trying to trace down the hundreds of closures all over the place that don't need to be there. It's **very** difficult for me to understand what exactly you're doing in your code, and I'm only trying to make a few simple changes.

Hopefully you'll get around to tidying it up, and standardizing it, as it has potential. Yes, I realize that you haven't committed in over a year, but OAuth hasn't died out so hopefully you get back on the project.

**Comment by marcusball** [comment]
I agree, this code is a bit difficult to follow. However, coincidentally, I just spent last night digging through it to add in a new feature, and I managed to get a slightly better grasp on it. Is there anything specific you're confused about or having issues with?

**Comment by CozyLife** [comment]
I was trying to remove the auto-redirects, but I've decided to use the PHP OAuth extension instead. It worked right out of the box without any problems. It's a breath of fresh air for me after trying to first program my own for a while, then searching for suitable third-party code.
